### ISSUE TITLE
Reading measurementData into Julia

### ISSUE THREAD

**Issue by paulflang** [paulflang/DisFit#4]
I created a new branch `multi_exp`.

Unfortunately reading of measurementData does not yet support multiple experimental conditions (see comments in `Disfit/DisFit/core.py` line 339 of the `multi_exp` branch for more details).

The current output code for Julia can be found in `DisFit/julia_code.jl` of the `multi_exp` branch.

@sshin23 : I am struggling to fix this. Could you please give it a try? Let me know if you need more info.

**Comment by sshin23** [comment]
@paulflang Please check [multi_exp 0f42f89] fix #4

**Comment by paulflang** [comment]
Thanks a lot, @sshin23 .
