### ISSUE TITLE
MUMPS requires more memory

### ISSUE THREAD

**Issue by paulflang** [paulflang/DisFit#5]
I just pushed c7cf5f31036030c7905d91306e05de6874514d78 to the `multi_exp` branch. I think the new code should correctly translate the PEtab problem specified in `Disfit/tests/fixtures/G2M_copasi` to a Julia JuMP problem (see `DisFit/julia_code.jl`). Unfortunately, when running the optimization I seem to run out of memory. @sshin23 : do you have any suggestions of how to solve this?
```
******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

This is Ipopt version 3.12.10, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:   288116
Number of nonzeros in inequality constraint Jacobian.:       16
Number of nonzeros in Lagrangian Hessian.............:   415260

MUMPS returned INFO(1) = -9 and requires more memory, reallocating.  Attempt 1
  Increasing icntl[13] from 1000 to 2000.
MUMPS returned INFO(1) = -9 and requires more memory, reallocating.  Attempt 2
  Increasing icntl[13] from 2000 to 4000.
```

**Comment by sshin23** [comment]
Made necessary changes in jump_script.jl in a1869ba. Could you make the corresponding changes in core.py? 

Also, it would be helpful to include a bash or python script for this example.

**Comment by paulflang** [comment]
Thanks a lot. I'll make the changes to core.py.
> Also, it would be helpful to include a bash or python script for this example.

Do you mean a script to run the translation of PEtab to JuMP?

**Comment by sshin23** [comment]
Hi Paul,

Also, it would be helpful to include a bash or python script for this
example.

Yes. Sorry if it was already in the repo and I wasn't finding it.

Thanks,
Sungho
